vkr/incidents/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy
from django.views.generic.base import RedirectView

from . import views

urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy('incidents')), name="index"),
    path("incident/<int:incident_id>", views.incident, name="incident"),
    path("incidents", views.incidents_list, name="incidents"),
    path("incident/create", views.incident_create, name="incident_create"),
    path("incident/<int:incident_id>/assess", views.incident_assess, name="incident_assess"),
    path("incident/<int:incident_id>/solved", views.incident_solved, name="incident_solved"),
    path("incident/<int:incident_id>/delete", views.incident_delete, name="incident_delete"),
    path("login", views.signin, name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("examples", views.examples, name="examples"),
    path("methods", views.methods, name="methods"),
]

vkr/vkr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("incidents.urls")),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vkr/incidents/models.py
from django.contrib.auth.models import User
from django.db import models


class Criteria(models.Model):
    description = models.CharField("Описание", max_length=200)

    def __str__(self) -> str:
        return self.description

    class Meta:
        verbose_name = "Критерий ранжирования"
        verbose_name_plural = "Критерии ранжирования"


class Expert(models.Model):
    user = models.OneToOneField(User, verbose_name="Пользователь", on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.get_full_name() + f" ({self.user.get_username()})"

    class Meta:
        verbose_name = "Эксперт"
        verbose_name_plural = "Эксперты"


class Status(models.Model):
    name = models.CharField("Наименование", max_length=100)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "Статус"
        verbose_name_plural = "Статусы"


class Incident(models.Model):
    name = models.CharField("Название", max_length=100)
    description = models.TextField("Описание")
    created_at = models.DateTimeField("Создан")
    results = models.TextField("Результаты", null=True, blank=True)

    creator = models.ForeignKey(
        Expert, verbose_name="Инициатор", on_delete=models.CASCADE,
        related_name="authored_incidents",
    )
    status = models.ForeignKey(Status, verbose_name="Статус", on_delete=models.CASCADE)

    criteries = models.ManyToManyField(Criteria, through="IncidentCriteria")
    experts = models.ManyToManyField(Expert, through="IncidentExpert")

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "Инцидент"
        verbose_name_plural = "Инциденты"


class Basis(models.Model):
    incident = models.ForeignKey(Incident, verbose_name="Инцидент", on_delete=models.CASCADE)

    name = models.CharField("Название", max_length=100)
    description = models.TextField("Описание")
    number = models.PositiveSmallIntegerField("Номер")

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "Базис инцидента"
        verbose_name_plural = "Базисы инцидента"
        unique_together = ('incident', 'name')


class Strategy(models.Model):
    incident = models.ForeignKey(Incident, verbose_name="Инцидент", on_delete=models.CASCADE)

    name = models.CharField("Название", max_length=100)
    description = models.TextField("Описание")
    number = models.PositiveSmallIntegerField("Номер")
    is_solution = models.BooleanField('Является решением', default=False)

    class Meta:
        verbose_name = "Стратегия устранения инцидента"
        verbose_name_plural = "Стратегии устранения инцидента"
        unique_together = ('incident', 'name')


class IncidentCriteria(models.Model):
    incident = models.ForeignKey(Incident, verbose_name="Инцидент", on_delete=models.CASCADE)
    criteria = models.ForeignKey(Criteria, verbose_name="Критерий", on_delete=models.CASCADE)
    number = models.PositiveSmallIntegerField("Номер")

    class Meta:
        verbose_name = "Критерий ранжирования инцидента"
        verbose_name_plural = "Критерии ранжирования инцидента"
        unique_together = ('incident', 'criteria')


class IncidentExpert(models.Model):
    incident = models.ForeignKey(Incident, verbose_name="Инцидент", on_delete=models.CASCADE)
    expert = models.ForeignKey(Expert, verbose_name="Эксперт", on_delete=models.CASCADE)
    number = models.PositiveSmallIntegerField("Номер")
    scores = models.TextField("Оценки", null=True, blank=True)

    class Meta:
        verbose_name = "Эксперт по инциденту"
        verbose_name_plural = "Эксперты по инциденту"
        unique_together = ('incident', 'expert')

vkr/incidents/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

from .models import Basis, Criteria, Incident, IncidentExpert, Strategy


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        label='Имя пользователя', label_suffix="",
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    password = forms.CharField(
        label='Пароль', label_suffix="",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = User
        fields = ['username', 'password']


class AssessmentForm(forms.Form):
    CHOICES = {
        '1/9': 'Очень сильно уступает (1/9)',
        '1/7': 'Значительно уступает (1/7)',
        '1/5': 'Сильно уступает (1/5)',
        '1/3': 'Умеренно уступает (1/3)',
        '1': 'Варианты равноценны (1)',
        '3': 'Умеренно превосходит (3)',
        '5': 'Сильно превосходит (5)',
        '7': 'Значительно превосходит (7)',
        '9': 'Очень сильно превосходит (9)',
    }
    choice = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-select-sm'}),
        choices=CHOICES, initial='1',
    )


class IncidentForm(forms.ModelForm):
    criteries_list = forms.ModelMultipleChoiceField(
        queryset=Criteria.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'mt-1'}),
        required=True,
        label="Критерии",
    )

    class Meta:
        model = Incident
        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control mt-1'}),
            'description': forms.Textarea(attrs={'class': 'form-control mt-1'}),
        }


class SolutionForm(forms.Form):
    choice = forms.ChoiceField(
        label="Пожалуйста, укажите стратегию, позволившую устранить инцидент",
        widget=forms.RadioSelect(attrs={'class': 'form-select-sm mb-2'}),
    )

    def __init__(self, *args, choices=None, **kwargs):
        super().__init__(*args, **kwargs)
        if choices is not None:
            self.fields['choice'].choices = [
                (choice.number - 1, choice.name)
                for choice in choices
            ] + [(len(choices), 'Инцидент не был решен')]


ExpertFormSet = forms.inlineformset_factory(
    Incident,
    IncidentExpert,
    fields=['expert'],
    widgets={'expert': forms.Select(attrs={'class': 'form-select-sm'})},
    extra=0,
    can_delete=False,
)


BasisFormSet = forms.inlineformset_factory(
    Incident,
    Basis,
    fields=['name', 'description'],
    widgets={
        'name': forms.TextInput(attrs={'class': 'form-control mt-1'}),
        'description': forms.Textarea(
            attrs={
                'class': 'form-control mt-1',
                'rows': 5,
            },
        ),
    },
    extra=0,
    can_delete=False,
    min_num=1,
    validate_min=True,
    max_num=7,
    validate_max=True,
)


StrategyFormSet = forms.inlineformset_factory(
    Incident,
    Strategy,
    fields=['name', 'description'],
    widgets={
        'name': forms.TextInput(attrs={'class': 'form-control mt-1'}),
        'description': forms.Textarea(
            attrs={
                'class': 'form-control mt-1',
                'rows': 5,
            },
        ),
    },
    extra=0,
    can_delete=False,
    min_num=2,
    validate_min=True,
    max_num=5,
    validate_max=True,
)

vkr/incidents/views.py
import json

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.db.models import Case, Count, When
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils import timezone

from .forms import (
    AssessmentForm,
    BasisFormSet,
    ExpertFormSet,
    IncidentForm,
    LoginUserForm,
    SolutionForm,
    StrategyFormSet,
)
from .models import Expert, Incident, IncidentExpert, Status, Strategy
from .utils.calculate import calculate_incident, get_all_scores, prepare_scores
from .utils.prepare_data import dict_decode, dict_encode, prepare_results


def signin(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('index')

        form = LoginUserForm()
        return render(request, 'incidents/login.html', {'form': form})

    elif request.method == 'POST':
        form = LoginUserForm(request, data=request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('incidents')

        return render(request, 'incidents/login.html', {'form': form})


@login_required(login_url='login')
def incidents_list(request) -> HttpResponse:
    incidents = Incident.objects.all().annotate(
        is_expert=Count(Case(When(experts__user=request.user, then=1))),
    ).order_by('-is_expert', 'status', '-created_at')

    return render(request, "incidents/incidents.html", {"incidents": incidents})


@login_required(login_url='login')
def incident_create(request) -> HttpResponseRedirect | HttpResponse:
    if request.method == 'GET':
        incident_form = IncidentForm()
        expert_formset = ExpertFormSet()
        basis_formset = BasisFormSet()
        strategy_formset = StrategyFormSet()
    elif request.method == 'POST':
        incident_form = IncidentForm(request.POST)
        expert_formset = ExpertFormSet(request.POST)
        basis_formset = BasisFormSet(request.POST)
        strategy_formset = StrategyFormSet(request.POST)

        if all([
            incident_form.is_valid(), expert_formset.is_valid(),
            basis_formset.is_valid(), strategy_formset.is_valid(),
        ]):
            incident = incident_form.save(commit=False)
            incident.created_at = timezone.now()
            incident.creator = Expert.objects.get(user=request.user)
            incident.status = Status.objects.get(name="Инициирован")
            incident.save()

            criteries = incident_form.cleaned_data['criteries_list']
            for num, criteria in enumerate(criteries):
                incident.incidentcriteria_set.create(criteria=criteria, number=num + 1)

            IncidentExpert.objects.create(
                incident=incident,
                expert=incident.creator,
                number=1,
            )
            experts_related = expert_formset.save(commit=False)
            experts_related = filter(
                lambda x: x.expert.user != incident.creator.user,
                experts_related,
            )
            for num, expert in enumerate(experts_related):
                expert.number = num + 2
                expert.incident = incident
                expert.save()

            basises_related = basis_formset.save(commit=False)
            for num, basis in enumerate(basises_related):
                basis.number = num + 1
                basis.incident = incident
                basis.save()

            strategies_related = strategy_formset.save(commit=False)
            for num, strategy in enumerate(strategies_related):
                strategy.number = num + 1
                strategy.incident = incident
                strategy.save()

            return redirect('incident', incident_id=incident.id)
    return render(
        request, 'incidents/incident_create.html',
        {
            'incident_form': incident_form, 'expert_formset': expert_formset,
            'basis_formset': basis_formset, 'strategy_formset': strategy_formset,
        },
    )


@login_required(login_url='login')
def incident_delete(request, incident_id):
    if request.method == 'POST':
        try:
            Incident.objects.get(id=incident_id).delete()
        except Incident.DoesNotExist:
            raise Http404("Инцидент не существует")
        return redirect("incidents")


@login_required(login_url='login')
def incident(request, incident_id):
    if request.method == 'GET':
        try:
            incident = Incident.objects.get(id=incident_id)
        except Incident.DoesNotExist:
            raise Http404("Инцидент не существует")

        try:
            expert = Expert.objects.get(user=request.user)
        except Expert.DoesNotExist:
            raise Http404("Эксперт не существует")

        experts_with_scores = IncidentExpert.objects.filter(
            incident=incident,
            scores__isnull=False,
        )
        incident_expert = IncidentExpert.objects.filter(
            incident=incident,
            expert=expert,
        ).first()
        results = prepare_results(incident)

        for expert in experts_with_scores:
            expert.scores = dict_decode(expert.scores)

        solution_form = SolutionForm(choices=incident.strategy_set.all())
        return render(
            request, "incidents/incident.html", {
                'incident': incident,
                'incident_expert': incident_expert,
                'is_active': (incident.status.name not in ('Решен', 'Отклонен')),
                'solution_form': solution_form,
                'experts_with_scores': experts_with_scores,
                'results': results,
            },
        )


@login_required(login_url='login')
def incident_assess(request, incident_id):
    if request.method == 'POST':
        try:
            incident = Incident.objects.get(id=incident_id)
        except Incident.DoesNotExist:
            raise Http404("Инцидент не существует")

        try:
            expert = Expert.objects.get(user=request.user)
        except Expert.DoesNotExist:
            raise Http404("Эксперт не существует")

        experts = IncidentExpert.objects.filter(incident=incident).all().order_by('number')

        done = True
        for expert_m in experts:
            if expert_m.expert_id == expert.id:
                incident_expert = expert_m
                incident_expert.scores = dict_encode(
                    prepare_scores(
                        json.loads(request.body),
                        incident.criteries.count(),
                        incident.strategy_set.count(),
                    ),
                )
                incident_expert.save()
            if expert_m.scores is None:
                done = False

        if done:
            incident.status = Status.objects.get(name="Оценен")
            incident.results = dict_encode(calculate_incident(get_all_scores(experts)))
            incident.save()
        elif incident.status.name == 'Инициирован':
            incident.status = Status.objects.get(name="В процессе оценивания")
            incident.save()

        return HttpResponse(status=200)

    else:
        try:
            incident = Incident.objects.get(id=incident_id)
        except Incident.DoesNotExist:
            raise Http404("Инцидент не существует")
        criteries = incident.criteries.all()
        basises = incident.basis_set.all()
        strategies = incident.strategy_set.all()
        assessment_form = AssessmentForm()
        return render(
            request, "incidents/incident_assess.html",
            {
                'incident': incident, 'assessment_form': assessment_form,
                'criteries': criteries, 'basises': basises, 'strategies': strategies,
            },
        )


@login_required(login_url='login')
def incident_solved(request, incident_id):
    if request.method == "POST":
        try:
            incident = Incident.objects.get(id=incident_id)
        except Incident.DoesNotExist:
            raise Http404("Инцидент не существует")

        strategy_number = int(json.loads(request.body)) + 1
        strategy = Strategy.objects.filter(incident=incident_id, number=strategy_number).first()
        if strategy is None:
            incident.status = Status.objects.get(name='Отклонен')
            incident.save()
        else:
            print(strategy.incident)
            strategy.is_solution = True
            strategy.save()
            incident.status = Status.objects.get(name='Решен')
            incident.save()

        return HttpResponse(status=200)


@login_required(login_url='login')
def examples(request):
    if request.method == 'GET':
        return render(request, "incidents/examples.html")


@login_required(login_url='login')
def methods(request):
    if request.method == 'GET':
        return render(request, "incidents/methods.html")

vkr/incidents/templates/incidents/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Решение инцидентов</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'incidents/css/bootstrap-icons.min.css' %}">
    <link rel="stylesheet" href="{% static 'incidents/css/style.css' %}">
    {% block links %}
    {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}

    {% block content %}
    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

vkr/incidents/templates/incidents/examples.html
{% extends 'incidents/base.html' %}
{% load static %}

{% block header %}
<header class="header fixed-top shadow-sm d-flex">
    <nav class="navbar navbar-expand-lg w-100">
        <a class="navbar-brand" href="#"></a>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
        <ul class="navbar-nav py-1">
            <li class="nav-item px-5"><a class="nav-link" href="{% url 'incidents' %}">Инциденты</a></li>
            <li class="nav-item px-5"><a class="nav-link" href="{% url 'methods' %}">Методы</a></li>
            <li class="nav-item px-5"><a class="nav-link active" href="{% url 'examples' %}">Примеры</a></li>
        </ul>
        </div>
        <ul class="navbar-nav position-fixed end-0 me-5 align-items-center">
            <li class="nav-item px-3 text-end mb-1">
                <div class="fullname">{{ request.user.get_full_name }}</div>
                <div class="username">({{ request.user.get_username }})</div>
            </li>
            <li class="nav-item px-3">
                <form action="{% url 'logout' %}" method="POST">
                    {% csrf_token %}
                    <button class="logout-btn" type="submit">Выйти</button>
                </form>
            </li>
          </ul>
    </nav>
</header>
{% endblock %}

vkr/incidents/templates/incidents/incident.html
{% extends 'incidents/base.html' %}
{% load static %}

{% block header %}
<header class="header fixed-top shadow-sm d-flex">
    <nav class="navbar navbar-expand-lg w-100">
        <a class="navbar-brand" href="#"></a>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
        <ul class="navbar-nav py-1">
            <li class="nav-item px-5"><a class="nav-link" href="{% url 'incidents' %}">Инциденты</a></li>
            <li class="nav-item px-5"><a class="nav-link" href="{% url 'methods' %}">Методы</a></li>
            <li class="nav-item px-5"><a class="nav-link" href="{% url 'examples' %}">Примеры</a></li>
        </ul>
        </div>
        <ul class="navbar-nav position-fixed end-0 me-5 align-items-center">
            <li class="nav-item px-3 text-end mb-1">
                <div class="fullname">{{ request.user.get_full_name }}</div>
                <div class="username">({{ request.user.get_username }})</div>
            </li>
            <li class="nav-item px-3">
                <form action="{% url 'logout' %}" method="POST">
                    {% csrf_token %}
                    <button class="logout-btn" type="submit">Выйти</button>
                </form>
            </li>
          </ul>
    </nav>
</header>
{% endblock %}
{% block content %}
<div class="cards d-flex p-2 flex-column align-items-center">
    <div class="col-lg-6 col-xxl-5 card mb-3">
        <div class="card-body mx-3 my-1">
          <h5 class="card-title">{{ incident.name }}</h5>
          <p class="card-text">{{ incident.description|linebreaks }}</p>
          <div class="row justify-content-between align-items-center py-3 border-top border-bottom">
            <p class="col card-subtitle text-warning"><i class="bi bi-info-circle"></i> {{ incident.status }}</p>
            <p class="col card-subtitle text-center text-muted"><i class="bi bi-person-gear"></i> {{ incident.creator.user.get_username }}</p>
            <p class="col card-subtitle text-muted text-end"><i class="bi bi-calendar-week"></i> {{ incident.created_at }}</p>
          </div>
          <!--  incident_expert and not incident_expert.scores  возможно лучше так -->
          {% if incident_expert and is_active %}
            <div class="row justify-content-between align-items-center pt-3">
              <a href="{% url 'incident_assess' incident.id %}" class="col btn btn-success">Оценить стратегии</a>
            </div>
          {% endif %}
          {% if request.user == incident.creator.user %}
            {% if experts_with_scores|length == incident.incidentexpert_set.all|length and is_active %}
              <div class="row justify-content-between align-items-center pt-3">
                <button type="button" class="col btn btn-solved btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
                  Завершить решение инцидента
                </button>
              </div>
              <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <form id="close-incident-form">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Завершить решение инцидента</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Отмена"></button>
                      </div>
                      <div class="modal-body">
                        {{ solution_form.as_p }}
                      </div>
                      <div class="modal-footer">
                          {% csrf_token %}
                          <button type="button" class="btn btn-success" id="close-incident-btn">Завершить</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            {% endif %}
            <form class="row justify-content-between align-items-center pt-3" action="{% url 'incident_delete' incident.id %}" method="POST">
              {% csrf_token %}
              <button class="col btn btn-danger" type="submit">Удалить инцидент</button>
            </form>
          {% endif %}
        </div>
        <div class="card-body mx-2 mb-1">
            <h5 class="card-title">Эксперты</h5>
            <ul class="list-group list-group-flush">
                {% for expert in incident.incidentexpert_set.all %}

                <li class="list-group-item">{{ forloop.counter }}. {{ expert.expert }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="card-body m-2 mb-1">
            <h5 class="card-title">Критерии</h5>
            <ul class="list-group list-group-flush">
                {% for criteria in incident.incidentcriteria_set.all %}
                <li class="list-group-item">{{ forloop.counter }}. {{ criteria.criteria }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="card-body m-2 mb-1">
            <h5 class="card-title">Базисы</h5>
            <div class="list-group">
                {% for basis in incident.basis_set.all %}
                <a class="list-group-item flex-column align-items-start">
                  <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ forloop.counter }}. {{ basis.name }}</h5>
                  </div>
                  <p class="mb-1">{{ basis.description|linebreaks }}</p>
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="card-body m-2 mb-1">
            <h5 class="card-title">Стратегии</h5>
            <div class="list-group">
                {% for strategy in incident.strategy_set.all %}
                <a class="list-group-item flex-column align-items-start">
                  <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ forloop.counter }}. {{ strategy.name }}</h5>
                  </div>
                  <p class="mb-1">{{ strategy.description|linebreaks }}</p>
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="card-body m-2 mb-1">
          <h5 class="card-title">Ценности стратегий на основе оценок экспертов</h5>
          {% if not experts_with_scores %}
            <p class="card-text">Ни один эксперт не предоставил своих оценок по инциденту.</p>
          {% else %}
            <div class="list-group">
              {% for expert in experts_with_scores %}
                <div class="list-group-item flex-column align-items-start">
                  <h5 class="mb-1">{{ expert.expert.user.get_full_name }} ({{ expert.expert.user.get_username }}):</h5>
                  <div class="accordion my-4" id="accordion{{ forloop.counter }}">
                    {% for bk, bv in expert.scores.V.items %}
                      <div class="accordion-item">
                        <h2 class="accordion-header">
                          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#e{{ forloop.parentloop.counter }}-collapse{{ forloop.counter }}" aria-expanded="true" aria-controls="e{{ forloop.parentloop.counter }}-collapse{{ forloop.counter }}">
                            Ценности стратегий по базису {{ forloop.counter }}
                          </button>
                        </h2>
                        <div id="e{{ forloop.parentloop.counter }}-collapse{{ forloop.counter }}" class="accordion-collapse collapse" data-bs-parent="#accordion{{ forloop.parentloop.counter }}">
                          <div class="accordion-body">
                            <p>Полученные на основе оценок эксперта ценности стратегий:</p>
                            <div class="border-start px-3 py-1">
                              {% for strategy_value in bv %}
                              <p class="mb-1">Стратегия {{ forloop.counter }}: {{ strategy_value|floatformat:4 }}</p>
                            {% endfor %}
                            </div>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                  </div>
                </div>
              {% endfor %}
            </div>
          {% endif %}
        </div>
        <div class="card-body m-2">
          <h5 class="card-title">Результаты</h5>
          {% if not incident.results %}
          <p class="card-text">Ранжирование стратегий по инциденту еще не расчитано.</p>
          {% else %}
          <form>
            <select class="form-select" id="dropdowncoeff">
              <option value="">Выберите критерий ранжирования</option>
              <option value="Q_vald">Критерий Вальда</option>
              <option value="Q_lapl">Критерий Лапласа</option>
              <option value="Q_sav">Критерий Севиджа</option>
              <option value="Q_hur">Критерий Гурвица</option>
              <option value="Q">Обобщенный критерий</option>
            </select>
          </form>
          {% endif %}
        </div>
      </div>
</div>
{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{{ results|json_script:"results-data" }}
<script type="text/javascript">
  $(document).ready(function() {
    const dropdowncoeff = document.querySelector("#dropdowncoeff");
    const results = JSON.parse(document.getElementById('results-data').textContent);

    $("#dropdowncoeff").on( "change", function() {
      var option_value = dropdowncoeff.options[dropdowncoeff.selectedIndex].value;
      var s = '';

      $("#ranging").remove();


      Object.keys(results[option_value]).forEach(function(key, index) {
        // console.log(results[option_value]);
        s += '<div class="w-100">'
              + '<h5 class="mb-1">' + String(index+1) + '. Стратегия №' + String(key[[key.length - 1]])
                + ' (' + results[option_value][key]['strategy_name'] +')' +
              '</h5>'
              + '<p class="mb-1">Итоговая ценность стратегии: ' + results[option_value][key]['value'] + '</p>'
            + '</div>'
      })
      $(
          '<div id="ranging" class="d-flex flex-column gap-2 pt-3">'
          + s
          + '</div>'
        ).insertAfter('#dropdowncoeff');
    });
    $("#close-incident-btn").click(async function () {
      const response = await fetch("{% url 'incident_solved' incident.id %}", {
        method: "POST",
        body: JSON.stringify($('#close-incident-form input[name="choice"]:checked').val()),
        headers: {'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value},
        mode: 'same-origin'
      });
      if (response) {$(location).attr('href', "{% url 'incident' incident.id %}");}
    });
  });
</script>
{% endblock %}